// --- src/codegen/fbs-generator.ts ---
import { ZodTypeAny, ZodObject } from "zod";

/**
 * Maps Zod types to their FlatBuffers schema counterparts.
 * @param type A Zod type object from the schema.
 * @returns The FlatBuffers type as a string.
 */
function zodToFbsType(type: ZodTypeAny): string {
  const typeName = type._def.typeName;
  switch (typeName) {
    case "ZodString":
      return "string";
    case "ZodNumber":
      return "double"; // Using double for general-purpose numbers
    case "ZodBoolean":
      return "bool";
    // TODO: Add support for more Zod types like arrays, dates, etc.
    default:
      throw new Error(`Unsupported Zod type for FBS generation: ${typeName}`);
  }
}

/**
 * Generates the full FlatBuffers schema (.fbs) file content as a string.
 * @param schema The schema object from the loaded graph config.
 * @returns The .fbs schema as a string.
 */
export function generateFbs(schema: any): string {
  const { nodes } = schema;
  const fbsTables: string[] = [];

  // Generate a table for each node type
  for (const nodeName in nodes) {
    const zodSchema = nodes[nodeName] as ZodObject<any>;
    const fields = Object.entries(
      zodSchema.shape as { [key: string]: ZodTypeAny }
    )
      .map(([fieldName, zodType]) => {
        return `  ${fieldName}:${zodToFbsType(zodType)};`;
      })
      .join("\n");

    const table = `table ${capitalize(nodeName)} {\n${fields}\n}`;
    fbsTables.push(table);
  }

  // Generate a table for storing relationship indices
  const idVectorTable = `
table IdVector {
  ids:[string];
}`;
  fbsTables.push(idVectorTable);

  // The root type could be used for schema evolution later if needed
  const rootType = `root_type ${capitalize(Object.keys(nodes)[0])};`;

  return `// Generated by @zgdb/cli\n\n${fbsTables.join(
    "\n\n"
  )}\n\n${rootType}\n`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
