// --- src/codegen/fbs-generator.ts ---
import { ZodTypeAny, ZodObject } from "zod";
import {
  ProcessedSchema,
  ProcessedEdge,
  capitalize,
} from "../schema-processor.js";

/**
 * Maps Zod types to their FlatBuffers schema counterparts.
 * @param type A Zod type object from the schema.
 * @returns The FlatBuffers type as a string.
 */
function zodToFbsType(type: ZodTypeAny): string {
  const typeName = type._def.typeName;
  switch (typeName) {
    case "ZodString":
      return "string";
    case "ZodNumber":
      return "double"; // Using double for general-purpose numbers
    case "ZodBoolean":
      return "bool";
    // TODO: Add support for more Zod types like arrays, dates, etc.
    default:
      throw new Error(`Unsupported Zod type for FBS generation: ${typeName}`);
  }
}

/**
 * Generates the full FlatBuffers schema (.fbs) file content as a string.
 * @param schema The processed schema object.
 * @returns The .fbs schema as a string.
 */
export function generateFbs(schema: ProcessedSchema): string {
  const { nodes, edges } = schema;
  const fbsTables: string[] = [];

  // Generate a table for each node type
  for (const nodeName in nodes) {
    const zodSchema = nodes[nodeName] as ZodObject<any>;

    // Get scalar fields from the Zod schema
    const scalarFields = Object.entries(
      zodSchema.shape as { [key: string]: ZodTypeAny }
    ).map(([fieldName, zodType]) => {
      return `  ${fieldName}:${zodToFbsType(zodType)};`;
    });

    // Get "to-one" relationship fields (foreign keys)
    const relationshipFields = edges
      .filter((edge: ProcessedEdge) => {
        // A field is added if this node is on the "many" side of a one-to-many relationship.
        const isTrueOneToMany =
          edge.cardinality === "one-to-many" &&
          !edge.name.backward.endsWith("s");
        return edge.target === nodeName && isTrueOneToMany;
      })
      .map((edge: ProcessedEdge) => {
        return `  ${edge.name.backward}:string;`;
      });

    const allFields = [...scalarFields, ...relationshipFields].join("\n");
    const table = `table ${capitalize(nodeName)} {\n${allFields}\n}`;
    fbsTables.push(table);
  }

  // Our generic "edge table" for storing to-many relationship indices.
  const idVectorTable = `table IdVector { ids:[string]; }`;
  fbsTables.push(idVectorTable);

  const rootType = `root_type ${capitalize(Object.keys(nodes)[0])};`;

  return `// Generated by @zgdb/cli\n\n${fbsTables.join(
    "\n\n"
  )}\n\n${rootType}\n`;
}
