/**
 * @file src/codegen/serializer-generator.ts
 * @description Generates the type-safe FlatBuffers serializers and data interfaces.
 */

import { z } from "zod";
import { Schema, getEdgeTables, ZodToTsType } from "./utils.js";

function capitalize(str: string): string {
  return str
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

// Helper to convert Zod schema to a TypeScript interface string for fields
function generateFieldsInterface(fields: z.ZodObject<any, any>): string {
  const shape = fields.shape;
  const fieldStrings = Object.keys(shape).map((key) => {
    const type = shape[key] as z.ZodTypeAny;
    return `  ${key}: ${ZodToTsType(type)};`;
  });
  return `{\n${fieldStrings.join("\n")}\n}`;
}

// Helper to generate relationIds interface string
function generateRelationsInterface(
  relations: Record<string, [string, string]>
): string {
  const relationStrings = Object.keys(relations).map((key) => {
    const [relationType] = relations[key];
    const tsType = relationType === "one" ? "string" : "string[]";
    return `  ${key}: ${tsType};`;
  });
  return `{\n${relationStrings.join("\n")}\n}`;
}

export function generateSerializer(schema: Schema): string {
  const lines: string[] = [];
  const nodeTypes = Object.keys(schema);
  const edgeTables = getEdgeTables(schema);
  const edgeTypes = Array.from(edgeTables.keys());

  // --- Imports ---
  lines.push(`import * as flatbuffers from 'flatbuffers';`);
  const allTypeNames = [...nodeTypes, ...edgeTypes].map(capitalize);
  lines.push(
    `import { ${allTypeNames.join(
      ", "
    )} } from './graph-db'; // Generated by flatc`
  );
  lines.push("");

  // --- Data Interfaces Generation ---
  lines.push("// ============================================");
  lines.push("//  Data Interfaces");
  lines.push("// ============================================");
  lines.push("");

  // Node data interfaces
  for (const nodeType of nodeTypes) {
    const { fields, relations } = schema[nodeType];
    const capitalizedName = capitalize(nodeType);
    lines.push(`export interface ${capitalizedName}Data {`);
    lines.push(`  id: string;`);
    lines.push(`  type: '${nodeType}';`);
    lines.push(`  createdAt: number;`);
    lines.push(`  updatedAt: number;`);
    lines.push(`  fields: ${generateFieldsInterface(fields)};`);
    lines.push(`  relationIds: ${generateRelationsInterface(relations)};`);
    lines.push(`}`);
    lines.push("");
  }

  // Edge data interfaces
  for (const edgeType of edgeTypes) {
    const edgeInfo = edgeTables.get(edgeType);
    if (!edgeInfo) continue;
    const capitalizedName = capitalize(edgeType);
    lines.push(`export interface ${capitalizedName}Data {`);
    lines.push(`  id: string;`);
    lines.push(`  type: '${edgeType}';`);
    lines.push(`  from: string; // ${edgeInfo.from} ID`);
    lines.push(`  to: string;   // ${edgeInfo.to} ID`);
    lines.push(`  createdAt: number;`);
    lines.push(`}`);
    lines.push("");
  }

  // --- Node Serializers ---
  lines.push("// ============================================");
  lines.push("//  Node Serializers");
  lines.push("// ============================================");
  lines.push("");

  const serializeNodeLines: string[] = [];
  for (const nodeType of nodeTypes) {
    const { fields, relations } = schema[nodeType];
    const capitalizedName = capitalize(nodeType);

    let serializerBody = `
    const builder = new flatbuffers.Builder(1024);
    const id = builder.createString(data.id);
`;
    for (const [fieldName, fieldType] of Object.entries(fields.shape)) {
      if ((fieldType as any)._def.typeName === "ZodString") {
        serializerBody += `    const ${fieldName} = builder.createString(data.fields.${fieldName});\n`;
      }
    }
    for (const [relationName, relationDef] of Object.entries(relations)) {
      const [relationType] = relationDef;
      serializerBody += `    const relationIds_${relationName} = Array.isArray(data.relationIds.${relationName}) ? data.relationIds.${relationName} : [data.relationIds.${relationName}];\n`;
      serializerBody += `    const ${relationName}Vector = ${capitalizedName}.create${capitalize(
        relationName
      )}IdsVector(builder, relationIds_${relationName}.map(id => builder.createString(id)));\n`;
    }

    serializerBody += `\n    ${capitalizedName}.start${capitalizedName}(builder);\n`;
    serializerBody += `    ${capitalizedName}.addId(builder, id);\n`;

    for (const [fieldName, fieldType] of Object.entries(fields.shape)) {
      if ((fieldType as any)._def.typeName === "ZodString") {
        serializerBody += `    ${capitalizedName}.add${capitalize(
          fieldName
        )}(builder, ${fieldName});\n`;
      } else {
        serializerBody += `    ${capitalizedName}.add${capitalize(
          fieldName
        )}(builder, data.fields.${fieldName});\n`;
      }
    }

    serializerBody += `    ${capitalizedName}.addCreatedAt(builder, BigInt(data.createdAt));\n`;
    serializerBody += `    ${capitalizedName}.addUpdatedAt(builder, BigInt(data.updatedAt));\n`;

    for (const [relationName] of Object.entries(relations)) {
      serializerBody += `    ${capitalizedName}.add${capitalize(
        relationName
      )}Ids(builder, ${relationName}Vector);\n`;
    }

    serializerBody += `    const root = ${capitalizedName}.end${capitalizedName}(builder);\n`;
    serializerBody += `    builder.finish(root);\n`;
    serializerBody += `    return builder.asUint8Array();\n`;

    serializeNodeLines.push(
      `  ${nodeType}: (data: ${capitalizedName}Data): Uint8Array => {${serializerBody}  }`
    );
  }
  lines.push(
    `export const serializeNode = {\n${serializeNodeLines.join(",\n")}\n};`
  );
  lines.push("");

  // --- Node Deserializers ---
  lines.push("// ============================================");
  lines.push("//  Node Deserializers");
  lines.push("// ============================================");
  lines.push("");
  const deserializeNodeLines: string[] = [];
  for (const nodeType of nodeTypes) {
    const { fields, relations } = schema[nodeType];
    const capitalizedName = capitalize(nodeType);
    let deserializerBody = `
    const buf = new flatbuffers.ByteBuffer(buffer);
    const table = ${capitalizedName}.getRootAs${capitalizedName}(buf);
    const relationIds: any = {};
`;
    for (const [relationName, relationDef] of Object.entries(relations)) {
      const [relationType] = relationDef;
      deserializerBody += `
    const ${relationName}Length = table.${relationName}IdsLength();
    if (${relationName}Length > 0) {
      const ids = Array.from({ length: ${relationName}Length }, (_, i) => table.${relationName}Ids(i)!);
      relationIds.${relationName} = ${
        relationType === "one" ? "ids[0]" : "ids"
      };
    }
`;
    }

    const fieldsObject = Object.keys(fields.shape)
      .map((fieldName) => `      ${fieldName}: table.${fieldName}()!`)
      .join(",\n");

    deserializerBody += `
    return {
      id: table.id()!,
      type: '${nodeType}',
      createdAt: Number(table.createdAt()),
      updatedAt: Number(table.updatedAt()),
      fields: {
${fieldsObject}
      },
      relationIds: relationIds as ${capitalizedName}Data['relationIds']
    };
`;
    deserializeNodeLines.push(
      `  ${nodeType}: (buffer: Uint8Array): ${capitalizedName}Data => {${deserializerBody}  }`
    );
  }
  lines.push(
    `export const deserializeNode = {\n${deserializeNodeLines.join(",\n")}\n};`
  );
  lines.push("");

  // --- Edge Serializers ---
  lines.push("// ============================================");
  lines.push("//  Edge Serializers");
  lines.push("// ============================================");
  lines.push("");

  const serializeEdgeLines: string[] = [];
  for (const edgeType of edgeTypes) {
    const edgeInfo = edgeTables.get(edgeType);
    if (!edgeInfo) continue;
    const capitalizedName = capitalize(edgeType);

    let serializerBody = `
    const builder = new flatbuffers.Builder(256);
    const id = builder.createString(data.id);
    const fromId = builder.createString(data.from);
    const toId = builder.createString(data.to);

    ${capitalizedName}.start${capitalizedName}(builder);
    ${capitalizedName}.addId(builder, id);
    ${capitalizedName}.add${capitalize(edgeInfo.from)}Id(builder, fromId);
    ${capitalizedName}.add${capitalize(edgeInfo.to)}Id(builder, toId);
    ${capitalizedName}.addCreatedAt(builder, BigInt(data.createdAt));
    const root = ${capitalizedName}.end${capitalizedName}(builder);

    builder.finish(root);
    return builder.asUint8Array();
`;
    serializeEdgeLines.push(
      `  ${edgeType}: (data: ${capitalizedName}Data): Uint8Array => {${serializerBody}  }`
    );
  }
  lines.push(
    `export const serializeEdge = {\n${serializeEdgeLines.join(",\n")}\n};`
  );
  lines.push("");

  // --- Edge Deserializers ---
  lines.push("// ============================================");
  lines.push("//  Edge Deserializers");
  lines.push("// ============================================");
  lines.push("");

  const deserializeEdgeLines: string[] = [];
  for (const edgeType of edgeTypes) {
    const edgeInfo = edgeTables.get(edgeType);
    if (!edgeInfo) continue;
    const capitalizedName = capitalize(edgeType);
    let deserializerBody = `
    const buf = new flatbuffers.ByteBuffer(buffer);
    const table = ${capitalizedName}.getRootAs${capitalizedName}(buf);
    return {
      id: table.id()!,
      type: '${edgeType}',
      from: table.${edgeInfo.from}Id()!,
      to: table.${edgeInfo.to}Id()!,
      createdAt: Number(table.createdAt()),
    };
`;
    deserializeEdgeLines.push(
      `  ${edgeType}: (buffer: Uint8Array): ${capitalizedName}Data => {${deserializerBody}  }`
    );
  }
  lines.push(
    `export const deserializeEdge = {\n${deserializeEdgeLines.join(",\n")}\n};`
  );
  lines.push("");

  // --- Supported Types ---
  lines.push("// ============================================");
  lines.push("//  Supported Type Constants");
  lines.push("// ============================================");
  lines.push("");
  lines.push(
    `export const supportedNodeTypes = [${nodeTypes
      .map((t) => `'${t}'`)
      .join(", ")}] as const;`
  );
  lines.push(
    `export const supportedEdgeTypes = [${edgeTypes
      .map((t) => `'${t}'`)
      .join(", ")}] as const;`
  );
  lines.push("");

  return lines.join("\n");
}
