// --- src/codegen/ts-generator.ts ---
import path from "path";
import fs from "fs/promises";
import { ProcessedSchema, capitalize } from "../schema-processor.js";

/**
 * Orchestrates the generation of all user-facing TypeScript files.
 * @param outputDir The directory to write the files to.
 * @param schema The processed schema from the config.
 * @param configPath The original path to the user's config file.
 */
export async function generateTsClient(
  outputDir: string,
  schema: ProcessedSchema,
  configPath: string
): Promise<void> {
  const runtimeDir = path.join(outputDir, "runtime");
  await fs.mkdir(runtimeDir, { recursive: true });

  // Find the relative path from the generated client to the user's config file.
  const relativeConfigPath = path
    .relative(outputDir, path.resolve(process.cwd(), configPath))
    .replace(/\\/g, "/")
    .replace(/\.ts$/, ".js"); // Ensure extension and slashes are correct for import

  await generateTypesFile(outputDir, schema, relativeConfigPath);
  await generateClientFile(outputDir, schema);
  await generateApiProxyHandler(runtimeDir);
  await generateNodeProxyHandler(runtimeDir);
}

async function generateTypesFile(
  outputDir: string,
  schema: ProcessedSchema,
  configPath: string
) {
  const { nodes, edges } = schema;
  const nodeNames = Object.keys(nodes);

  // Import base types inferred from the user's Zod schemas
  const baseTypeImports = nodeNames
    .map((name) => `${capitalize(name)} as Base${capitalize(name)}`)
    .join(", ");
  const importStatement = `import type { ${baseTypeImports} } from '${configPath}';`;

  // Generate augmented types with relationship properties
  const augmentedTypes = nodeNames
    .map((nodeName) => {
      const relatedFields = edges
        .map((edge) => {
          if (edge.source === nodeName) {
            const targetType = capitalize(edge.target);
            return `  ${edge.name.forward}: ${
              edge.cardinality === "one-to-many"
                ? `${targetType}[]`
                : `${targetType}`
            };`;
          }
          if (edge.target === nodeName) {
            const sourceType = capitalize(edge.source);
            return `  ${edge.name.backward}: ${
              edge.cardinality === "one-to-many"
                ? `${sourceType}`
                : `${sourceType}[]`
            };`;
          }
          return null;
        })
        .filter(Boolean)
        .join("\n");

      return `export type ${capitalize(nodeName)} = Base${capitalize(
        nodeName
      )} & {\n${relatedFields}\n};`;
    })
    .join("\n\n");

  const content = `// Generated by @zgdb/cli\n${importStatement}\n\n${augmentedTypes}\n`;
  await fs.writeFile(path.join(outputDir, "types.ts"), content, "utf8");
}

async function generateClientFile(outputDir: string, schema: ProcessedSchema) {
  const { nodes } = schema;
  const nodeNames = Object.keys(nodes);

  const typesImport = nodeNames.map(capitalize).join(", ");
  const collections = nodeNames
    .map((name) => `    ${name}: Map<string, ${capitalize(name)}>;`)
    .join("\n");

  const proxyInitializers = nodeNames
    .map(
      (name) =>
        `    client.${name} = new Proxy(new Map(), createApiProxyHandler(db, client, '${name}'));`
    )
    .join("\n");

  const content = `// Generated by @zgdb/cli
import { PTree } from 'prolly-gunna';
import type { ${typesImport} } from './types.js';
import { createApiProxyHandler } from './runtime/api-proxy-handler.js';

export type ZgDbClient = {
${collections}
};

export function createClient(ptree?: PTree): ZgDbClient {
    const db = ptree || new PTree();
    const client = {} as ZgDbClient;
    
${proxyInitializers}

    return client;
}
`;
  await fs.writeFile(path.join(outputDir, "client.ts"), content, "utf8");
}

async function generateApiProxyHandler(runtimeDir: string) {
  const content = `// Generated by @zgdb/cli. Runtime logic goes here.
import { PTree } from 'prolly-gunna';
import { ZgDbClient } from '../client.js';

export function createApiProxyHandler(ptree: PTree, client: ZgDbClient, nodeName: string) {
    return {
        get(target: Map<string, any>, id: string) {
            console.log(\`[GET] Request for \${nodeName} with id: \${id}\`);
            // TODO: PTree lookup, deserialization, and node proxy creation logic.
            return target.get(id);
        },
        set(target: Map<string, any>, id: string, value: any): boolean {
            console.log(\`[SET] Request for \${nodeName} with id: \${id}\`);
            // TODO: PTree insertion/update, serialization, and index update logic.
            return target.set(id, value);
        }
    };
}
`;
  await fs.writeFile(
    path.join(runtimeDir, "api-proxy-handler.ts"),
    content,
    "utf8"
  );
}

async function generateNodeProxyHandler(runtimeDir: string) {
  const content = `// Generated by @zgdb/cli. Runtime logic goes here.
import { PTree } from 'prolly-gunna';
import { ZgDbClient } from '../client.js';
import * as flatbuffers from 'flatbuffers';

export function createNodeProxyHandler(ptree: PTree, client: ZgDbClient, buffer: flatbuffers.ByteBuffer, nodeName: string) {
    return {
        get(target: flatbuffers.ByteBuffer, prop: string | symbol) {
            if (typeof prop === 'symbol') return undefined;
            console.log(\`Accessing '\${prop}' on \${nodeName}\`);
            // TODO: Differentiate between scalar and relation properties.
            // For scalars: use FlatBuffers accessors.
            // For relations: use PTree index lookups.
            return \`value for \${prop}\`;
        }
    };
}
`;
  await fs.writeFile(
    path.join(runtimeDir, "node-proxy-handler.ts"),
    content,
    "utf8"
  );
}
