// --- src/codegen/ts-generator.ts ---
import path from "path";
import fs from "fs/promises";
import {
  ProcessedSchema,
  ProcessedEdge,
  capitalize,
} from "../schema-processor.js";

/**
 * Orchestrates the generation of all user-facing TypeScript files.
 * @param outputDir The directory to write the files to.
 * @param schema The processed schema from the config.
 */
export async function generateTsClient(
  outputDir: string,
  schema: ProcessedSchema
): Promise<void> {
  const runtimeDir = path.join(outputDir, "runtime");
  await fs.mkdir(runtimeDir, { recursive: true });

  await generateTypesFile(outputDir, schema);
  await generateClientFile(outputDir, schema);
  await generateCollectionFile(outputDir);
  await generateNodeProxyHandler(runtimeDir);
}

async function generateTypesFile(outputDir: string, schema: ProcessedSchema) {
  const { nodes, edges } = schema;
  const nodeNames = Object.keys(nodes);

  const importStatement = `import { z } from 'zod';\nimport graphConfig from './graph.config.js';`;

  // Define the final, fully-augmented interfaces first. This allows TypeScript
  // to resolve the circular type dependencies correctly.
  const interfaces = nodeNames
    .map((nodeName) => {
      const capNodeName = capitalize(nodeName);
      const baseType = `z.infer<typeof graphConfig.schema.nodes.${nodeName}>`;

      const relationFields = edges
        .map((edge) => {
          if (edge.source === nodeName) {
            const targetType = capitalize(edge.target);
            return `  ${edge.name.forward}: ${
              edge.name.forward.endsWith("s") ? `${targetType}[]` : targetType
            };`;
          }
          if (edge.target === nodeName) {
            const sourceType = capitalize(edge.source);
            return `  ${edge.name.backward}: ${
              edge.name.backward.endsWith("s") ? `${sourceType}[]` : sourceType
            };`;
          }
          return null;
        })
        .filter(Boolean)
        .join("\n");

      return `export interface ${capNodeName} extends ${baseType} {\n${relationFields}\n}`;
    })
    .join("\n\n");

  // Now, define the Zod schemas using z.lazy() to handle the runtime circular dependencies.
  const zodSchemas = nodeNames
    .map((nodeName) => {
      const capNodeName = capitalize(nodeName);
      const relationFields = edges
        .map((edge) => {
          if (edge.source === nodeName) {
            const targetType = capitalize(edge.target);
            const fieldType = edge.name.forward.endsWith("s")
              ? `z.array(z.lazy(() => ${targetType}Schema))`
              : `z.lazy(() => ${targetType}Schema)`;
            return `  ${edge.name.forward}: ${fieldType},`;
          }
          if (edge.target === nodeName) {
            const sourceType = capitalize(edge.source);
            const fieldType = edge.name.backward.endsWith("s")
              ? `z.array(z.lazy(() => ${sourceType}Schema))`
              : `z.lazy(() => ${sourceType}Schema)`;
            return `  ${edge.name.backward}: ${fieldType},`;
          }
          return null;
        })
        .filter(Boolean)
        .join("\n");

      return `export const ${capNodeName}Schema: z.ZodType<${capNodeName}> = graphConfig.schema.nodes.${nodeName}.extend({\n${relationFields}\n});`;
    })
    .join("\n\n");

  // Finally, define the creation input types.
  const creationInputTypes = nodeNames
    .map((nodeName) => {
      const capNodeName = capitalize(nodeName);
      const baseCreationType = `z.infer<typeof graphConfig.schema.nodes.${nodeName}>`;
      const creationRelationFields = edges
        .filter(
          (edge) =>
            edge.target === nodeName && !edge.name.backward.endsWith("s")
        )
        .map(
          (edge) =>
            `  ${edge.name.backward}: z.infer<typeof graphConfig.schema.nodes.${edge.source}>;`
        )
        .join("\n");

      return `export type ${capNodeName}CreationInput = ${baseCreationType} & {\n${creationRelationFields}\n};`;
    })
    .join("\n\n");

  const content = `// Generated by @zgdb/cli
${importStatement}

// --- Final Augmented Interfaces ---
// These are the full TypeScript types for your nodes, including all relationships.
// They are defined first to allow TypeScript to resolve circular dependencies.
${interfaces}

// --- Augmented Zod Schemas ---
// These Zod schemas are extended from your base schemas in graph.config.ts
// to include full relationship validation, using z.lazy() to handle circularity.
${zodSchemas}

// --- Creation Input Types ---
// These types define the shape of the data needed to create a new node.
${creationInputTypes}
`;
  await fs.writeFile(path.join(outputDir, "types.ts"), content, "utf8");
}

async function generateClientFile(outputDir: string, schema: ProcessedSchema) {
  const { nodes } = schema;
  const nodeNames = Object.keys(nodes);

  const typesImport = nodeNames.map(capitalize).join(", ");
  const creationTypesImport = nodeNames
    .map((name) => `${capitalize(name)}CreationInput`)
    .join(", ");

  const collections = nodeNames
    .map((name) => {
      const capName = capitalize(name);
      return `    ${name}: Collection<${capName}, ${capName}CreationInput>;`;
    })
    .join("\n");

  const initializers = nodeNames
    .map(
      (name) =>
        `    client.${name} = new Collection<${capitalize(name)}, ${capitalize(
          name
        )}CreationInput>(db, client as ZgDbClient, '${name}');`
    )
    .join("\n");

  const content = `// Generated by @zgdb/cli
import { PTree } from 'prolly-gunna';
import type { ${typesImport}, ${creationTypesImport} } from './types.js';
import { Collection } from './collection.js';

export type ZgDbClient = {
${collections}
};

export function createClient(ptree?: PTree): ZgDbClient {
    const db = ptree || new PTree();
    const client = {} as ZgDbClient;
    
${initializers}

    return client;
}
`;
  await fs.writeFile(path.join(outputDir, "client.ts"), content, "utf8");
}

async function generateCollectionFile(outputDir: string) {
  const content = `// Generated by @zgdb/cli
import { PTree } from 'prolly-gunna';
import type { ZgDbClient } from './client.js';
import { createNodeProxyHandler } from './runtime/node-proxy-handler.js';

/**
 * A strongly-typed, iterable collection that provides the API for interacting
 * with a set of nodes (e.g., all Users, all Posts).
 */
export class Collection<T, TCreationInput> implements Iterable<T> {
    
    constructor(
        private ptree: PTree,
        private client: ZgDbClient,
        private nodeName: string
    ) {}

    add(value: TCreationInput): T {
        console.log(\`[ADD] \${this.nodeName} with id: \${(value as any).id}\`);
        // TODO: Actual PTree write logic goes here.
        
        // For now, we return a mock proxy to satisfy the type.
        // In the real implementation, this would be a proxy over a FlatBuffer.
        const mockBuffer = {} as any; 
        return new Proxy(mockBuffer, createNodeProxyHandler(this.ptree, this.client, mockBuffer, this.nodeName, value as any)) as T;
    }

    get(id: string): T | undefined {
        console.log(\`[GET] \${this.nodeName} with id: \${id}\`);
        // TODO: Actual PTree read logic goes here.
        return undefined;
    }

    values(): IterableIterator<T> {
        return this[Symbol.iterator]();
    }

    *[Symbol.iterator](): IterableIterator<T> {
        console.log(\`[ITERATE] over \${this.nodeName}\`);
        // TODO: PTree scan logic goes here.
        yield* [];
    }
}

// This is the key: we explicitly define the methods on the prototype
// and mark them as non-enumerable, just like native JavaScript classes.
Object.defineProperties(Collection.prototype, {
    add: { enumerable: false },
    get: { enumerable: false },
    values: { enumerable: false },
});
`;
  await fs.writeFile(path.join(outputDir, "collection.ts"), content, "utf8");
}

async function generateNodeProxyHandler(runtimeDir: string) {
  const content = `// Generated by @zgdb/cli. Runtime logic goes here.
import { PTree } from 'prolly-gunna';
import { ZgDbClient } from '../client.js';
import * as flatbuffers from 'flatbuffers';

// This is a temporary mock. The real proxy will wrap a FlatBuffer.
type MockTarget = {
    buffer: flatbuffers.ByteBuffer,
    data: any, // For now, we store the raw data for easy access.
}

export function createNodeProxyHandler(ptree: PTree, client: ZgDbClient, buffer: flatbuffers.ByteBuffer, nodeName: string, data: any) {
    
    const target = { buffer, data };

    return {
        get(target: MockTarget, prop: string | symbol) {
            if (typeof prop === 'symbol') return undefined;

            // Return scalar properties directly from the mocked data.
            if (prop in target.data) {
                return target.data[prop];
            }
            
            // TODO: Real relationship logic will go here, involving PTree lookups.
            console.log(\`Accessing '\${prop}' on \${nodeName}, returning empty array for now.\`);
            return [];
        }
    };
}
`;
  await fs.writeFile(
    path.join(runtimeDir, "node-proxy-handler.ts"),
    content,
    "utf8"
  );
}
