// --- src/codegen/ts-generator.ts ---
import path from "path";
import fs from "fs/promises";
import {
  ProcessedSchema,
  ProcessedEdge,
  capitalize,
} from "../schema-processor.js";

/**
 * Orchestrates the generation of all user-facing TypeScript files.
 * @param outputDir The directory to write the files to.
 * @param schema The processed schema from the config.
 */
export async function generateTsClient(
  outputDir: string,
  schema: ProcessedSchema
): Promise<void> {
  const runtimeDir = path.join(outputDir, "runtime");
  await fs.mkdir(runtimeDir, { recursive: true });

  await generateTypesFile(outputDir, schema);
  await generateClientFile(outputDir, schema);
  await generateApiProxyHandler(runtimeDir);
  await generateNodeProxyHandler(runtimeDir);
}

async function generateTypesFile(outputDir: string, schema: ProcessedSchema) {
  const { nodes, edges } = schema;
  const nodeNames = Object.keys(nodes);

  const importStatement = `import { z } from 'zod';\nimport graphConfig from './graph.config.js';`;

  const augmentedSchemas = nodeNames
    .map((nodeName) => {
      const capNodeName = capitalize(nodeName);
      const baseNodeSchema = `graphConfig.schema.nodes.${nodeName}`;

      const relatedFields = edges
        .map((edge: ProcessedEdge) => {
          const sourceCap = capitalize(edge.source);
          const targetCap = capitalize(edge.target);
          if (edge.source === nodeName) {
            const fieldType = edge.name.forward.endsWith("s")
              ? `z.array(z.lazy(() => ${targetCap}Schema))`
              : `z.lazy(() => ${targetCap}Schema)`;
            return `  ${edge.name.forward}: ${fieldType},`;
          }
          if (edge.target === nodeName) {
            const fieldType = edge.name.backward.endsWith("s")
              ? `z.array(z.lazy(() => ${sourceCap}Schema))`
              : `z.lazy(() => ${sourceCap}Schema)`;
            return `  ${edge.name.backward}: ${fieldType},`;
          }
          return null;
        })
        .filter(Boolean)
        .join("\n");

      return `const ${capNodeName}Schema = ${baseNodeSchema}.extend({\n${relatedFields}\n});`;
    })
    .join("\n\n");

  const finalTypes = nodeNames
    .map((nodeName) => {
      const capNodeName = capitalize(nodeName);
      return `export type ${capNodeName} = z.infer<typeof ${capNodeName}Schema>;`;
    })
    .join("\n");

  const creationInputTypes = nodeNames
    .map((nodeName) => {
      const capNodeName = capitalize(nodeName);
      const baseNodeSchema = `graphConfig.schema.nodes.${nodeName}`;
      const baseNodeCreationSchema = `graphConfig.schema.nodes.${nodeName}`;

      const creationInputRelatedFields = edges
        .filter(
          (edge) =>
            edge.target === nodeName && !edge.name.backward.endsWith("s")
        )
        .map((edge) => {
          const sourceCreationSchema = `graphConfig.schema.nodes.${edge.source}`;
          return `  ${edge.name.backward}: z.infer<typeof ${sourceCreationSchema}>,`;
        })
        .join("\n");

      return `export type ${capNodeName}CreationInput = z.infer<typeof ${baseNodeCreationSchema}> & {\n${creationInputRelatedFields}\n};`;
    })
    .join("\n\n");

  const content = `// Generated by @zgdb/cli
${importStatement}

// --- Augmented Zod Schemas with Relationships ---
// These schemas are extended from your base schemas in graph.config.ts
// to include relationship fields. z.lazy() is used to handle circular dependencies.

// TypeScript needs to know the type of the schema before it is used in z.lazy()
// So we declare them all first with a base type.
${nodeNames
  .map((name) => `let ${capitalize(name)}Schema: z.ZodObject<any>;`)
  .join("\n")}

${augmentedSchemas}

// --- Final TypeScript Types ---
// These are the final, fully-featured types for your nodes, including relationships.
${finalTypes}

// --- Creation Input Types ---
// These types define the data needed to create a new node.
${creationInputTypes}
`;
  await fs.writeFile(path.join(outputDir, "types.ts"), content, "utf8");
}

async function generateClientFile(outputDir: string, schema: ProcessedSchema) {
  const { nodes } = schema;
  const nodeNames = Object.keys(nodes);

  const typesImport = nodeNames.map(capitalize).join(", ");
  const creationTypesImport = nodeNames
    .map((name) => `${capitalize(name)}CreationInput`)
    .join(", ");

  const collectionInterface = `
export interface Collection<T, TCreationInput> extends Iterable<T> {
    add(value: TCreationInput): T;
    get(id: string): T | undefined;
    values(): IterableIterator<T>;
}`;

  const collections = nodeNames
    .map((name) => {
      const capName = capitalize(name);
      return `    ${name}: Collection<${capName}, ${capName}CreationInput>;`;
    })
    .join("\n");

  const proxyInitializers = nodeNames
    .map((name) => {
      const capName = capitalize(name);
      return `    client.${name} = new Proxy({} as Collection<${capName}, ${capName}CreationInput>, createApiProxyHandler(db, client, '${name}'));`;
    })
    .join("\n");

  const content = `// Generated by @zgdb/cli
import { PTree } from 'prolly-gunna';
import type { ${typesImport}, ${creationTypesImport} } from './types.js';
import { createApiProxyHandler } from './runtime/api-proxy-handler.js';

${collectionInterface}

export type ZgDbClient = {
${collections}
};

export function createClient(ptree?: PTree): ZgDbClient {
    const db = ptree || new PTree();
    const client = {} as ZgDbClient;
    
${proxyInitializers}

    return client;
}
`;
  await fs.writeFile(path.join(outputDir, "client.ts"), content, "utf8");
}

async function generateApiProxyHandler(runtimeDir: string) {
  const content = `// Generated by @zgdb/cli. Runtime logic goes here.
import { PTree } from 'prolly-gunna';
import { ZgDbClient, Collection } from '../client.js';

export function createApiProxyHandler<T, TCreationInput>(ptree: PTree, client: ZgDbClient, nodeName: string): ProxyHandler<Collection<T, TCreationInput>> {
    const handler: ProxyHandler<Collection<T, TCreationInput>> = {
        get(target, prop, receiver) {
            if (prop === 'add') {
                return (value: TCreationInput) => {
                    console.log(\`[ADD] Request for \${nodeName} with id: \${(value as any).id}\`);
                    // TODO: PTree insertion/update, serialization, and index update logic.
                    // For now, just return the value for API compatibility, cast to T
                    return value as any as T;
                }
            }
            if (prop === 'get') {
                return (id: string): T | undefined => {
                    console.log(\`[GET] Request for \${nodeName} with id: \${id}\`);
                    // TODO: PTree lookup, deserialization, and node proxy creation logic.
                    return undefined;
                }
            }
            if (prop === 'values' || prop === Symbol.iterator) {
                return function* (): IterableIterator<T> {
                    console.log(\`[ITERATE] Iterating over \${nodeName}\`);
                    // TODO: PTree scan logic.
                    yield* [];
                }
            }
            return Reflect.get(target, prop, receiver);
        }
    };
    return handler;
}
`;
  await fs.writeFile(
    path.join(runtimeDir, "api-proxy-handler.ts"),
    content,
    "utf8"
  );
}

async function generateNodeProxyHandler(runtimeDir: string) {
  const content = `// Generated by @zgdb/cli. Runtime logic goes here.
import { PTree } from 'prolly-gunna';
import { ZgDbClient } from '../client.js';
import * as flatbuffers from 'flatbuffers';

export function createNodeProxyHandler(ptree: PTree, client: ZgDbClient, buffer: flatbuffers.ByteBuffer, nodeName: string) {
    return {
        get(target: flatbuffers.ByteBuffer, prop: string | symbol) {
            if (typeof prop === 'symbol') return undefined;
            console.log(\`Accessing '\${prop}' on \${nodeName}\`);
            // TODO: Differentiate between scalar and relation properties.
            // For scalars: use FlatBuffers accessors.
            // For relations: use PTree index lookups.
            return \`value for \${prop}\`;
        }
    };
}
`;
  await fs.writeFile(
    path.join(runtimeDir, "node-proxy-handler.ts"),
    content,
    "utf8"
  );
}
