// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * A reaction from a user to a specific piece of content, like a post or a comment.
 */
export class Reaction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Reaction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReaction(bb:flatbuffers.ByteBuffer, obj?:Reaction):Reaction {
  return (obj || new Reaction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReaction(bb:flatbuffers.ByteBuffer, obj?:Reaction):Reaction {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Reaction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

authorId():string|null
authorId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
authorId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

targetId():string|null
targetId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
targetId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

targetType():string|null
targetType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
targetType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startReaction(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addAuthorId(builder:flatbuffers.Builder, authorIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, authorIdOffset, 0);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, idOffset, 0);
}

static addTargetId(builder:flatbuffers.Builder, targetIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, targetIdOffset, 0);
}

static addTargetType(builder:flatbuffers.Builder, targetTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, targetTypeOffset, 0);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, typeOffset, 0);
}

static endReaction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReaction(builder:flatbuffers.Builder, authorIdOffset:flatbuffers.Offset, idOffset:flatbuffers.Offset, targetIdOffset:flatbuffers.Offset, targetTypeOffset:flatbuffers.Offset, typeOffset:flatbuffers.Offset):flatbuffers.Offset {
  Reaction.startReaction(builder);
  Reaction.addAuthorId(builder, authorIdOffset);
  Reaction.addId(builder, idOffset);
  Reaction.addTargetId(builder, targetIdOffset);
  Reaction.addTargetType(builder, targetTypeOffset);
  Reaction.addType(builder, typeOffset);
  return Reaction.endReaction(builder);
}
}
