// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * Nested schema for metadata of Image
 */
export class ImageMetadata {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ImageMetadata {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsImageMetadata(bb:flatbuffers.ByteBuffer, obj?:ImageMetadata):ImageMetadata {
  return (obj || new ImageMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsImageMetadata(bb:flatbuffers.ByteBuffer, obj?:ImageMetadata):ImageMetadata {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ImageMetadata()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

width():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mutate_width(value:bigint):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt64(this.bb_pos + offset, value);
  return true;
}

height():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mutate_height(value:bigint):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt64(this.bb_pos + offset, value);
  return true;
}

format():string|null
format(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
format(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdAt():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

mutate_created_at(value:bigint):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt64(this.bb_pos + offset, value);
  return true;
}

static startImageMetadata(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addWidth(builder:flatbuffers.Builder, width:bigint) {
  builder.addFieldInt64(0, width, BigInt('0'));
}

static addHeight(builder:flatbuffers.Builder, height:bigint) {
  builder.addFieldInt64(1, height, BigInt('0'));
}

static addFormat(builder:flatbuffers.Builder, formatOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, formatOffset, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAt:bigint) {
  builder.addFieldInt64(3, createdAt, BigInt('0'));
}

static endImageMetadata(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createImageMetadata(builder:flatbuffers.Builder, width:bigint, height:bigint, formatOffset:flatbuffers.Offset, createdAt:bigint):flatbuffers.Offset {
  ImageMetadata.startImageMetadata(builder);
  ImageMetadata.addWidth(builder, width);
  ImageMetadata.addHeight(builder, height);
  ImageMetadata.addFormat(builder, formatOffset);
  ImageMetadata.addCreatedAt(builder, createdAt);
  return ImageMetadata.endImageMetadata(builder);
}
}
