// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

/**
 * The join entity connecting a Post and a Tag.
 */
export class PostTag {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PostTag {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPostTag(bb:flatbuffers.ByteBuffer, obj?:PostTag):PostTag {
  return (obj || new PostTag()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPostTag(bb:flatbuffers.ByteBuffer, obj?:PostTag):PostTag {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PostTag()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

postId():string|null
postId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
postId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tagId():string|null
tagId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tagId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPostTag(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addPostId(builder:flatbuffers.Builder, postIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, postIdOffset, 0);
}

static addTagId(builder:flatbuffers.Builder, tagIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, tagIdOffset, 0);
}

static endPostTag(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPostTag(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, postIdOffset:flatbuffers.Offset, tagIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  PostTag.startPostTag(builder);
  PostTag.addId(builder, idOffset);
  PostTag.addPostId(builder, postIdOffset);
  PostTag.addTagId(builder, tagIdOffset);
  return PostTag.endPostTag(builder);
}
}
